---
title: "Examining Trends in Montana"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
    pandoc_args: 
      - "--wrap=preserve"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../_posts") })
date: 2023-08-29
permalink: /posts/2023/08/treasure-state
toc: true
tags:
  - Montana
  - youth voting
---

```{r}
tester2018 <- read.csv("tester2018.csv", colClasses = "character")
bq2022 <- read.csv("bq2022.csv")
turnout <- read.csv("turnout.csv")
```

```{r}
library(tidyverse)
bq2022$YES <- as.numeric(gsub(",", "", bq2022$YES))
bq2022$NO <- as.numeric(gsub(",", "", bq2022$NO))
bq2022 <- bq2022 %>%
  mutate(TOTALVOTES.22 = YES + NO,
         NO.TWAY = NO / TOTALVOTES.22,
         NET.NO = NO-YES) %>%
    select(County, NO.TWAY,TOTALVOTES.22, NO, YES, NET.NO)

tester2018$TESTER <- as.numeric(gsub(",", "", tester2018$TESTER))
tester2018$ROSENDALE <- as.numeric(gsub(",", "", tester2018$ROSENDALE))
tester2018$county_fips = tester2018$FIPS.code
tester2018$county_fips <- paste0("30", tester2018$county_fips)



tester2018 <- tester2018 %>%
  mutate(TOTALVOTES.18 = TESTER+ROSENDALE,
         TESTER.TWAY = TESTER / TOTALVOTES.18,
         NET.TESTER = TESTER-ROSENDALE) %>%
  select(County, county_fips,TESTER.TWAY, TOTALVOTES.18, 
         TESTER,ROSENDALE, NET.TESTER)
```

```{r}
mtdat <- merge(tester2018, bq2022)
mtdat <- merge(mtdat, turnout)
mtdat = subset(mtdat, County != "TOTALS")

mtdat <- mtdat %>% mutate(
  diff = TESTER.TWAY - NO.TWAY,
  turnout.diff = turnout.2022 - turnout.2018,
  turnout.diff.z = (turnout.diff - -0.08324821)/0.05260116,
  turnout.diff.demean = (turnout.diff - -0.08324821)
)
```

```{r}
library(ggplot2) # load in first to avoid issues with fortify()
library(tidyverse)
library(urbnmapr) # to get shapefiles
library(scales) # needed for rescale()
library(sf)
library(rgdal)
#library(maps)
library(maptools)



minimum <- countydata %>%
  left_join(counties, by = "county_fips") %>% 
  filter(state_name =="Montana") %>%
  select(long, lat, county_fips) #extracting county shape info

df3 <- full_join(minimum, mtdat, by='county_fips') # merge election results and county shapefiles

```


```{r}
# Min: -0.2045489
# Max: 0.2515544
# recall zi = (xi – min(x)) / (max(x) – min(x)) * 100
# Desired midpoint (xi): 0 pct
# rescale from (-0.2045489,0.2515544) to (-1,1) and find what 0 maps to in (-1,1)
# so, we get: (0 + 20.45489) / (25.15544+20.45489) * 100 = 44.84706

margin22 <- ggplot(df3, mapping = aes(long, lat, group = county_fips, fill = diff))+
  geom_polygon(color = "#000000", size = .25) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_fill_gradientn(values=rescale(c(0,0.4484706,1)),
                       colours=c("#5aa9e6","#859de9", "white", 
                                          "#ec976d", "#E9724C"),
                       guide = "colourbar",
                       aesthetics = "fill",
                       breaks=c(-.20,-.10,0,.10,.20),
                       labels=c("LR-131:'NO' +20%","LR-131:'NO' +10%", "0%", "Tester 2018 +10%", "Tester 2018 +20%"))+
  theme_minimal()

margin22
```

```{r center points}
# https://stackoverflow.com/questions/9441778/improve-centering-county-names-ggplot-maps

cnames <- df3 %>% group_by(County) %>%
    summarize_at(vars(long, lat), ~ mean(range(.)))

cnames2 <- cbind(cnames, mtdat$NET.TESTER, mtdat$NET.NO, mtdat$county_fips) %>%
  mutate(NET.TESTER = mtdat$NET.TESTER,
         NET.NO = mtdat$NET.NO,
         county_fips = mtdat$county_fips) %>%
  select(County, long, lat, NET.TESTER, NET.NO, county_fips)
```



```{r}

tester.net.plot <- ggplot(df3, mapping = aes(long, lat, 
                                             group = county_fips)) + 
  geom_point(data=cnames2, aes(long, lat, fill = NET.TESTER, colour = NET.TESTER, size=NET.TESTER)) +
  geom_polygon(color = "#000000", fill=NA, size = .25) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) + 
  scale_fill_gradient2() +
  theme_minimal()


tester.net.plot + theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      panel.grid.major=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.title = element_text(hjust = 0),
      plot.title = element_text(hjust = 0.05,size = 22),
      plot.caption = element_text(hjust = 1, face = "italic", size=10)) 
```



```{r}
# Min: -3.268973
# Max: 2.649147
# recall zi = (xi – min(x)) / (max(x) – min(x)) * 100
# Desired midpoint (xi): 0 pct
# rescale from (-3.268973,2.649147) to (-1,1) and find what 0 maps to in (-1,1)
# so, we get: (0 + 3.268973) / (2.649147+3.268973) * 100 = 55.23668

turnoutshifts <- ggplot(df3, mapping = aes(long, lat, group = county_fips, fill = turnout.diff.z))+
  geom_polygon(color = "#000000", size = .25) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_fill_gradientn(values=rescale(c(0,0.5523668,1)),
                       colours=c("#6b2d5c","#a9245e", "white", 
                                          "#B53E2E", "#ff4e00"),
                       guide = "colourbar",
                       aesthetics = "fill",
                       breaks=c(-3, -2,-1,0,1,2),
                       labels=c("z=-3","z=-2", "z=-1", "z=0", "z=1", "z=2")) +
  theme_minimal()
turnoutshifts
```


```{r}
mapmargin22 <- margin22 + theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      panel.grid.major=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.title = element_text(hjust = 0),
      plot.title = element_text(hjust = 0.05,size = 22),
      plot.caption = element_text(hjust = 1, face = "italic", size=10)) +
      ggtitle("2018 Tester Senate v. 2022 Referendum 131 Results") +
  labs(caption = "Statewide two-way total: Tester 2018 51.8%, Referendum 131 'NO' 52.6%\nMap: Zachary L. Hertz\n@zacharylhertz\nData: MT SOS",
       fill = "Difference in Two-Way\nVote Share")
mapmargin22
```

```{r}
mapturnoutshifts <- turnoutshifts + theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      panel.grid.major=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.title = element_text(hjust = 0),
      plot.title = element_text(hjust = 0.05,size = 22),
      plot.caption = element_text(hjust = 1, face = "italic", size=10)) +
      ggtitle("Standardized 2018-2022 Turnout Shifts in Montana") +
  labs(caption = "Statewide turnout decreased by 10.2 percentage points between 2018 and 2022.\nPurple counties saw turnout drop faster than the county-level average shift.\nOrange counties had turnout shifts less negative than the county-level average shift.\nMap: Zachary L. Hertz\n@zacharylhertz\nData: MT SOS",
       fill = "Z-Score for 2018-2022 \nCounty Turnout Shift")
mapturnoutshifts
```


```{r}
ggplot(mtdat, aes(x=turnout.diff, y=diff)) + 
  geom_point() +
  geom_smooth(method=lm, se=FALSE)
```
```{r}
library(tidycensus)
mt.dat <- get_estimates(geography = "county", 
                             product = "characteristics", 
                             breakdown = c("SEX", "AGEGROUP", "HISP"),  
                             breakdown_labels = TRUE, 
                             state = "MT",
                             year = 2021)
```




```{r read in data, include=FALSE}
library(haven)
ces10 <- read_dta("../../../Archived/CCES/data/2010 data/cces_2010_common_validated.dta")
ces12 <- read_dta("../../../Archived/CCES/data/2012 data/CCES12_Common_VV.dta")
ces14 <- read_dta("../../../Archived/CCES/data/2014 data/CCES14_Common_Content_Validated.dta")
ces16 <- read_dta("../../../Archived/CCES/data/2016 data/CCES16_Common_OUTPUT_VV.dta")
ces18 <- read_dta("../../../Archived/CCES/data/2018 data/cces18_common_vv.dta")
ces20 <- read.csv("../../../Archived/CCES/data/2020 data/CES20_Common_OUTPUT_vv.csv")
```

```{r}
ces10 <- subset(ces10, V302 == 30)
ces12 <- subset(ces12, inputstate == 30)
ces14 <- subset(ces14, inputstate == 30)
ces16 <- subset(ces16, inputstate == 30)
ces18 <- subset(ces18, inputstate == 30)
ces20 <- subset(ces20, inputstate == 30)
```


```{r recoding, include=FALSE}
# recode age from birth year
ces10$age <- 2010-ces10$V207
ces12$age <- 2012-ces12$birthyr
ces14$age <- 2014-ces14$birthyr
ces16$age <- 2016-ces16$birthyr
ces18$age <- 2018-ces18$birthyr
ces20$age <- 2020-ces20$birthyr

# binary youth variable
ces10$youth[ces10$age<30] <- 1
ces10$youth[ces10$age>29] <- 0
ces12$youth[ces12$age<30] <- 1
ces12$youth[ces12$age>29] <- 0
ces14$youth[ces14$age<30] <- 1
ces14$youth[ces14$age>29] <- 0
ces16$youth[ces16$age<30] <- 1
ces16$youth[ces16$age>29] <- 0
ces18$youth[ces18$age<30] <- 1
ces18$youth[ces18$age>29] <- 0
ces20$youth[ces20$age<30] <- 1
ces20$youth[ces20$age>29] <- 0

# binary kiddo variable
ces10$kiddo[ces10$age<20] <- 1
ces10$kiddo[ces10$age>19] <- 0
ces12$kiddo[ces12$age<20] <- 1
ces12$kiddo[ces12$age>19] <- 0
ces14$kiddo[ces14$age<20] <- 1
ces14$kiddo[ces14$age>19] <- 0
ces16$kiddo[ces16$age<20] <- 1
ces16$kiddo[ces16$age>19] <- 0
ces18$kiddo[ces18$age<20] <- 1
ces18$kiddo[ces18$age>19] <- 0
ces20$kiddo[ces20$age<20] <- 1
ces20$kiddo[ces20$age>19] <- 0

# 26th amendment age variable
ces10$yvtr[ces10$age<21] <- 1
ces10$yvtr[ces10$age>20] <- 0
ces12$yvtr[ces12$age<21] <- 1
ces12$yvtr[ces12$age>20] <- 0
ces14$yvtr[ces14$age<21] <- 1
ces14$yvtr[ces14$age>20] <- 0
ces16$yvtr[ces16$age<21] <- 1
ces16$yvtr[ces16$age>20] <- 0
ces18$yvtr[ces18$age<21] <- 1
ces18$yvtr[ces18$age>20] <- 0
ces20$yvtr[ces20$age<21] <- 1
ces20$yvtr[ces20$age>20] <- 0

# Validated Turnout ####
ces10$voted <- 0
ces10$voted[ces10$vote_gen10==1] <- 1
ces12$voted <- 0
ces12$voted[ces12$e2012g!="MatchedNoVote" & ces12$e2012g != ""] <- 1
ces14$voted <- 0
ces14$voted[ces14$e2014gvm!=""] <- 1
ces16$voted <- 0
ces16$voted[ces16$CL_E2016GVM!=""] <- 1
ces18$voted <- 0
ces18$voted[is.na(ces18$CL_2018gvm)==FALSE] <- 1
ces20$voted <- 0
ces20$voted[is.na(ces20$CL_2020gvm)==FALSE] <- 1

# Self reported voter reg
ces10$votereg <- ces10$V203
ces10$votereg_post <- ces10$V203_post
ces10$saidreg <- 0
ces10$saidreg[ces10$votereg_post==1] <- 1
ces12$saidreg <- 0
ces12$saidreg[ces12$votereg_post==1] <- 1
ces14$saidreg <- 0
ces14$saidreg[ces14$votereg_post==1] <- 1
ces16$saidreg <- 0
ces16$saidreg[ces16$votereg_post==1] <- 1
ces18$saidreg <- 0
ces18$saidreg[ces18$votereg_post==1] <- 1
ces20$saidreg <- 0
ces20$saidreg[ces20$votereg_post==1] <- 1


# Self reported voting
ces10$saidvote <- 0
ces10$saidvote[ces10$CC401==5] <- 1
ces12$saidvote <- 0
ces12$saidvote[ces12$CC401==5] <- 1
ces14$saidvote <- 0
ces14$saidvote[ces14$CC401==5] <- 1
ces16$saidvote <- 0
ces16$saidvote[ces16$CC16_401==5] <- 1
ces18$saidvote <- 0
ces18$saidvote[ces18$CC18_401==5] <- 1
ces20$saidvote <- 0
ces20$saidvote[ces20$CC20_401==5] <- 1
```

```{r design objects, include=FALSE}
library(survey)
ces10.wt <- svydesign(ids=~1, data=ces10,
                     weights=ces10$V101)
ces12.wt <- svydesign(ids=~1, data=ces12,
                     weights=ces12$V103)
ces14.wt <- svydesign(ids=~1, data=ces14,
                     weights=ces14$weight)
ces16.wt <- svydesign(ids=~1, data=ces16,
                     weights=ces16$commonweight_post)
ces18 <- subset(ces18, is.na(ces18$commonpostweight)==FALSE)
ces18.wt <- svydesign(ids=~1, data=ces18,
                     weights=ces18$commonpostweight)
ces20 <- subset(ces20, is.na(ces20$commonpostweight)==FALSE)
ces20.wt <- svydesign(ids=~1, data=ces20,
                     weights=ces20$commonpostweight)
```


```{r 2010, include=FALSE}
library(magrittr)
# 2010 voters
voted.10 <- svytable(~saidvote, 
                     design=ces10.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

voted.10$year <- 2010
voted.10$group <- "All adults"

yv.10 <- subset(ces10.wt, yvtr==1)
youth.10 <- subset(ces10.wt, youth==1)

y.voted.10 <- svytable(~saidvote, 
                     design=yv.10) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.voted.10$year <- 2010
y.voted.10$group <- "Adults ages 18-20"


# 2010 registration
registered.10 <- svytable(~saidreg, 
                     design=ces10.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

registered.10$year <- 2010
registered.10$group <- "All adults"

y.registered.10 <- svytable(~saidreg, 
                     design=yv.10) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.registered.10$year <- 2010
y.registered.10$group <- "Adults ages 18-20"

```


```{r 2012, include=FALSE}
# 2012 voters
voted.12 <- svytable(~saidvote, 
                     design=ces12.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

voted.12$year <- 2012
voted.12$group <- "All adults"

yv.12 <- subset(ces12.wt, yvtr==1)
youth.12 <- subset(ces12.wt, youth==1)

y.voted.12 <- svytable(~saidvote, 
                     design=yv.12) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.voted.12$year <- 2012
y.voted.12$group <- "Adults ages 18-20"


# 2012 registration
registered.12 <- svytable(~saidreg, 
                     design=ces12.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

registered.12$year <- 2012
registered.12$group <- "All adults"

y.registered.12 <- svytable(~saidreg, 
                     design=yv.12) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.registered.12$year <- 2012
y.registered.12$group <- "Adults ages 18-20"
```

```{r 2014, include=FALSE}
# 2014 voters
voted.14 <- svytable(~saidvote, 
                     design=ces14.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

voted.14$year <- 2014
voted.14$group <- "All adults"

yv.14 <- subset(ces14.wt, yvtr==1)
youth.14 <- subset(ces14.wt, youth==1)

y.voted.14 <- svytable(~saidvote, 
                     design=yv.14) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.voted.14$year <- 2014
y.voted.14$group <- "Adults ages 18-20"


# 2014 registration
registered.14 <- svytable(~saidreg, 
                     design=ces14.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

registered.14$year <- 2014
registered.14$group <- "All adults"

y.registered.14 <- svytable(~saidreg, 
                     design=yv.14) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.registered.14$year <- 2014
y.registered.14$group <- "Adults ages 18-20"
```

```{r 2016, include=FALSE}
# 2016 voters
voted.16 <- svytable(~saidvote, 
                     design=ces16.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

voted.16$year <- 2016
voted.16$group <- "All adults"

yv.16 <- subset(ces16.wt, yvtr==1)
youth.16 <- subset(ces16.wt, youth==1)

y.voted.16 <- svytable(~saidvote, 
                     design=yv.16) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.voted.16$year <- 2016
y.voted.16$group <- "Adults ages 18-20"


# 2016 registration
registered.16 <- svytable(~saidreg, 
                     design=ces16.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

registered.16$year <- 2016
registered.16$group <- "All adults"

y.registered.16 <- svytable(~saidreg, 
                     design=yv.16) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.registered.16$year <- 2016
y.registered.16$group <- "Adults ages 18-20"
```


```{r 2018, include=FALSE}
# 2018 voters
voted.18 <- svytable(~saidvote, 
                     design=ces18.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

voted.18$year <- 2018
voted.18$group <- "All adults"

yv.18 <- subset(ces18.wt, yvtr==1)
youth.18 <- subset(ces18.wt, youth==1)

y.voted.18 <- svytable(~saidvote, 
                     design=yv.18) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.voted.18$year <- 2018
y.voted.18$group <- "Adults ages 18-20"


# 2018 registration
registered.18 <- svytable(~saidreg, 
                     design=ces18.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

registered.18$year <- 2018
registered.18$group <- "All adults"

y.registered.18 <- svytable(~saidreg, 
                     design=yv.18) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.registered.18$year <- 2018
y.registered.18$group <- "Adults ages 18-20"
```

```{r 2020, include=FALSE}
# 2020 voters
voted.20 <- svytable(~saidvote, 
                     design=ces20.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

voted.20$year <- 2020
voted.20$group <- "All adults"

yv.20 <- subset(ces20.wt, yvtr==1)
youth.20 <- subset(ces20.wt, youth==1)

y.voted.20 <- svytable(~saidvote, 
                     design=yv.20) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.voted.20$year <- 2020
y.voted.20$group <- "Adults ages 18-20"


# 2020 registration
registered.20 <- svytable(~saidreg, 
                     design=ces20.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

registered.20$year <- 2020
registered.20$group <- "All adults"

y.registered.20 <- svytable(~saidreg, 
                     design=yv.20) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.registered.20$year <- 2020
y.registered.20$group <- "Adults ages 18-20"
```


```{r validated votes}
# 2010 validated voters
valvote.10 <- svytable(~voted, 
                     design=ces10.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

valvote.10$year <- 2010
valvote.10$group <- "All adults"

y.valvote.10 <- svytable(~voted, 
                     design=yv.10) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.valvote.10$year <- 2010
y.valvote.10$group <- "Adults ages 18-20"

youth.valvote.10 <- svytable(~voted, 
                     design=youth.10) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

youth.valvote.10$year <- 2010
youth.valvote.10$group <- "Adults ages 18-29"

# 2012 validated voters
valvote.12 <- svytable(~voted, 
                     design=ces12.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

valvote.12$year <- 2012
valvote.12$group <- "All adults"

y.valvote.12 <- svytable(~voted, 
                     design=yv.12) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.valvote.12$year <- 2012
y.valvote.12$group <- "Adults ages 18-20"

youth.valvote.12 <- svytable(~voted, 
                     design=youth.12) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

youth.valvote.12$year <- 2012
youth.valvote.12$group <- "Adults ages 18-29"

# 2014 validated voters
valvote.14 <- svytable(~voted, 
                     design=ces14.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

valvote.14$year <- 2014
valvote.14$group <- "All adults"

y.valvote.14 <- svytable(~voted, 
                     design=yv.14) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.valvote.14$year <- 2014
y.valvote.14$group <- "Adults ages 18-20"

youth.valvote.14 <- svytable(~voted, 
                     design=youth.14) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

youth.valvote.14$year <- 2014
youth.valvote.14$group <- "Adults ages 18-29"

# 2016 validated voters
valvote.16 <- svytable(~voted, 
                     design=ces16.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

valvote.16$year <- 2016
valvote.16$group <- "All adults"

y.valvote.16 <- svytable(~voted, 
                     design=yv.16) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.valvote.16$year <- 2016
y.valvote.16$group <- "Adults ages 18-20"

youth.valvote.16 <- svytable(~voted, 
                     design=youth.16) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

youth.valvote.16$year <- 2016
youth.valvote.16$group <- "Adults ages 18-29"

# 2018 validated voters

valvote.18 <- svytable(~voted, 
                     design=ces18.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

valvote.18$year <- 2018
valvote.18$group <- "All adults"

y.valvote.18 <- svytable(~voted, 
                     design=yv.18) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.valvote.18$year <- 2018
y.valvote.18$group <- "Adults ages 18-20"

youth.valvote.18 <- svytable(~voted, 
                     design=youth.18) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

youth.valvote.18$year <- 2018
youth.valvote.18$group <- "Adults ages 18-29"

# 2020 validated voters
valvote.20 <- svytable(~voted, 
                     design=ces20.wt) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

valvote.20$year <- 2020
valvote.20$group <- "All adults"

y.valvote.20 <- svytable(~voted, 
                     design=yv.20) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

y.valvote.20$year <- 2020
y.valvote.20$group <- "Adults ages 18-20"

youth.valvote.20 <- svytable(~voted, 
                     design=youth.20) %>%
  prop.table() %>%
  multiply_by(100) %>%  
  round(digits=1) %>%
  as.data.frame()

youth.valvote.20$year <- 2020
youth.valvote.20$group <- "Adults ages 18-29"
```


```{r combine data, include=FALSE}
valvote.data <- rbind(valvote.10, y.valvote.10, 
                   valvote.12, y.valvote.12,
                   valvote.14, y.valvote.14,
                   valvote.16, y.valvote.16,
                   valvote.18, y.valvote.18,
                   valvote.20, y.valvote.20)

valvote.y.data <- rbind(valvote.10, youth.valvote.10, 
                   valvote.12, youth.valvote.12,
                   valvote.14, youth.valvote.14,
                   valvote.16, youth.valvote.16,
                   valvote.18, youth.valvote.18,
                   valvote.20, youth.valvote.20)

vote.data <- rbind(voted.10, y.voted.10, 
                   voted.12, y.voted.12,
                   voted.14, y.voted.14,
                   voted.16, y.voted.16,
                   voted.18, y.voted.18,
                   voted.20, y.voted.20)

reg.data <- rbind(registered.10, y.registered.10, 
                  registered.12, y.registered.12,
                  registered.14, y.registered.14,
                  registered.16, y.registered.16,
                  registered.18, y.registered.18,
                  registered.20, y.registered.20)

reg.data$year <- as.factor(reg.data$year)
vote.data$year <- as.factor(vote.data$year)
valvote.data$year <- as.factor(valvote.data$year)
valvote.y.data$year <- as.factor(valvote.y.data$year)


vote.data.youth <- subset(vote.data, group=="Adults ages 18-20")
reg.data.youth <- subset(reg.data, group=="Adults ages 18-20")

export <- subset(valvote.y.data, voted==1 & group=="Adults ages 18-29")

write.csv(export, "youth-voting-data2.csv")
```

```{r ns for interpretation, include=FALSE}
year <- c(2010, 2012, 2014, 2016, 2018, 2020)
totalyouth <- c(700, 1409, 1471, 2126, 867, 777)
n.dat <- as.data.frame(cbind(year, totalyouth))
n.dat$year <- as.factor(n.dat$year)
```


```{r plots, include=FALSE}
library(tidyverse)

p.n <- ggplot(data=n.dat, aes(x=year, y=totalyouth, group=1)) + 
  geom_line(size=1.5, color="#52528C") +
  theme_minimal() +
  ylim(300,2500) +
  theme(plot.title = element_text(hjust = 0.20, 
                                  size = 19), 
        plot.caption = element_text(hjust = 1,
                                    face = "italic", size=12),
        axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=15),
        axis.text.x = element_text(size=13, 
                                   color = "black"),
        axis.text.y = element_text(size=13, 
                                   color = "black")) + 
  ylab("Number of Respondents \nAge 18-20") +
  xlab("Year") +
  labs(caption = "Zachary L. Hertz | Data: CES") +
  ggtitle("Total number of respondents ages 18-20 \nhave dropped in recent CES releases")

p.reg <- ggplot(data=subset(reg.data, saidreg!=0), 
                aes(x=year, y=Freq, group=group, color=group)) + 
  geom_line(size=1.5) + theme_minimal() +
  theme(plot.title = element_text(hjust = 0.20, 
                                  size = 19), 
        plot.caption = element_text(hjust = 1,
                                    face = "italic", size=12),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text=element_text(size=13),
        axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=15),
        axis.text.x = element_text(size=13, 
                                   color = "black"),
        axis.text.y = element_text(size=13, 
                                   color = "black")) + 
  ylab("Percent Registered to Vote \n(Self-Reported)") +
  xlab("Year") +
  labs(caption = "Zachary L. Hertz | Data: CES") +
  scale_color_manual(values=c("#66A182", "#031927")) +
  ggtitle("The voter registration gap between all adults and \nthose 18-20 decreased in 2016 but has persisted")

p.vote <- ggplot(data=subset(vote.data, saidvote!=0), 
                 aes(x=year, y=Freq, group=group, color=group)) + 
  geom_line(size=1.5) + theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 19), 
        plot.caption = element_text(hjust = 1,
                                    face = "italic", size=12),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text=element_text(size=13),
        axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=15),
        axis.text.x = element_text(size=13, 
                                   color = "black"),
        axis.text.y = element_text(size=13, 
                                   color = "black")) + 
  ylab("Percent Voted \n(Self-Reported)") +
  xlab("Year") +
  labs(caption = "Zachary L. Hertz | Data: CES") +
  scale_color_manual(values=c("#66A182", "#031927")) +
  ggtitle("Self-reported vote among adults \nage 18-20 has broadly increased")

p.valvote <- ggplot(data=subset(valvote.data, voted!=0), 
                 aes(x=year, y=Freq, group=group, color=group)) + 
  geom_line(size=1.5) + theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 19), 
        plot.caption = element_text(hjust = 1,
                                    face = "italic", size=12),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text=element_text(size=13),
        axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=15),
        axis.text.x = element_text(size=13, 
                                   color = "black"),
        axis.text.y = element_text(size=13, 
                                   color = "black")) + 
  ylab("Percent Voted") +
  xlab("Year") +
  labs(caption = "Zachary L. Hertz | Data: CES") +
  scale_color_manual(values=c("#66A182", "#031927")) +
  ggtitle("")

p.y.valvote <- ggplot(data=subset(valvote.y.data, voted!=0), 
                 aes(x=year, y=Freq, group=group, color=group)) + 
  geom_line(size=1.5) + theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 19), 
        plot.caption = element_text(hjust = 1,
                                    face = "italic", size=12),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text=element_text(size=13),
        axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=15),
        axis.text.x = element_text(size=13, 
                                   color = "black"),
        axis.text.y = element_text(size=13, 
                                   color = "black")) + 
  ylab("Percent Voted") +
  xlab("Year") +
  labs(caption = "Zachary L. Hertz | Data: CES") +
  scale_color_manual(values=c("#D87CAC", "#031927")) +
  ggtitle("")


```


```{r}
model <- lm(NO.TWAY ~ TESTER.TWAY, data=mtdat)
standard_res <- rstandard(model)
mtdat <- cbind(mtdat, standard_res)
mtdat$abs.st.res = abs(mtdat$standard_res)

library(ggrepel)
library(ggpp)
p <- ggplot(mtdat, aes(x=TESTER.TWAY, y=NO.TWAY)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  geom_text_repel(aes(label=ifelse(abs.st.res>0.9,as.character(County),'')),
                  hjust=0,vjust=0,
                  box.padding = 0.4, 
                  point.padding = 0.5,
                  segment.color = 'grey50',
                  direction="x",
                  position = position_nudge_line(x = 0, y = 0.04,
                                              method = "lm",
                                              direction = "split")) +
  theme(axis.line=element_blank(),
      axis.ticks=element_blank(),
      panel.grid.major=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      plot.title = element_text(hjust = 1, size = 22),
      plot.caption = element_text(hjust = 1, face = "italic", size=10)) +
      ggtitle("County-Level 2018 Tester Senate v. 2022 Referendum 131 Results") +
  labs(caption = "Statewide two-way total: Tester 2018 51.8%, Referendum 131 'NO' 52.6%\nPlot: Zachary L. Hertz\n@zacharylhertz\nData: MT SOS",
       x = "Jon Tester 2018 Two-Way Vote Share",
       y = "LR-131 'NO' 2022 Two-Way Vote Share") +
  theme_minimal()
p
```

```{r}

ggsave("scatter.png", width = 7.3, height = 5, units = c("in"), dpi=700)
```


```{r}
mdat <- filter(mtdat, TESTER.TWAY > 0.5)
```

PLACEHOLDER TEXT


